# Docs: https://github.com/Azure/webapps-deploy
# Pipeline: Build & Deploy Spring Boot JAR to Azure Web App

name: Build and Deploy Spring Boot JAR to Azure - Alpha

on:
  push:
    branches:
      - main   # Se ejecuta cuando haces push a main
  workflow_dispatch: # Permite correrlo manualmente desde GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1821BD95A2EA4DB38F521065A494B1C1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_020101F98F3C40B88EF2B5994BE42544 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AC9060AE6B504A75946B48BB45196FD3 }}

      - name: Wait before deployment
        run: sleep 10

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sturdy'   # Nombre de tu App Service
          slot-name: 'Production'
          package: '*.jar'
          scm-do-build-during-deployment: true

      - name: Check deployed app health
        run: |
          echo "Verificando despliegue..."
          curl -I https://sturdy-h3b6f4fyc5fbeuae.westeurope-01.azurewebsites.net || exit 1
          
